name: Run phpunit test all Plugins

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  phpunit-test-suite:
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD:
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1]
        cms: [dev-develop]
        version: [dev-master]
        plugin: [juzaweb/subscription]
    name: PHP ${{ matrix.php }} - CMS ${{ matrix.cms }} - ${{ matrix.os }}

    steps:
      - name: Test plugin ${{ matrix.plugin }}
        uses: juzaweb/actions/.github/workflows/plugin-test.yml@main
        with:
          plugin: ${{ matrix.plugin }}
